In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [19]:
df=pd.read_excel('coronaClean.xlsx')
df

,Unnamed: 0,Age,Sex,coronaTest,Previous_history_of_corona,Then,Cough,Muscular_pain,respiratory_distress,Loss_of_consciousness,...,Chronic_liver_diseases,diabetes,Chronic blood diseases,Immunodeficiency,pregnancy,Heart_disease,Chronic_kidney_diseases,Asthma,History_of_hypertension,Assignment_status
0,0,40.0,1,0,0,1,1,0,0,0,...,0,0,0,0,0,1,0,0,3,0
1,1,34.0,1,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,3,0
2,2,43.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,4,1
3,3,33.0,1,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,3,0
4,4,57.0,1,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157746,157746,64.0,0,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,1,1,0
157747,157747,49.0,0,1,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,2,0
157748,157748,61.0,1,0,0,0,0,0,1,1,...,0,0,0,0,1,0,0,1,1,0
157749,157749,0.9,1,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3,0
157750,157750,82.0,1,0,0,1,0,0,1,1,...,0,0,0,0,0,0,0,1,1,0

In [20]:
del df['Unnamed: 0']

In [4]:
#remove irrevalant features with RF exe

li = ['Previous_history_of_corona','Immunodeficiency',
      'Inflammation_skin lesion','Limb plegia']

df_c = df.drop(li,axis=1)

### Ø¨Ø¯ÙˆÙ† Ø§Ù†ØªØ®Ø§Ø¨ ÙˆÛŒÚ˜Ú¯ÛŒ

In [21]:
X=df.drop('Assignment_status',axis=1)

Y= df['Assignment_status']

### Ø¨Ø§ Ø§Ù†ØªØ®Ø§Ø¨ ÙˆÛŒÚ˜Ú¯ÛŒ#

In [5]:
X=df_c.drop('Assignment_status',axis=1)

Y= df_c['Assignment_status']

### ØªÙ‚Ø³ÛŒÙ… Ø¯Ø§Ø¯Ù‡ Ù‡Ø§ Ø¨Ù‡ Ø¢Ù…ÙˆØ²Ø´ÛŒ Ùˆ ØªØ³Øª

In [22]:

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,
                                               random_state=42,shuffle=True)

In [23]:
x_train.shape

(118313, 37)

In [25]:

#layers for fully connected
from keras.models import Sequential
from keras.layers import Dense

classifier=Sequential()

#first layer in fc(MLP with two layers - 9 attributes)


classifier.add(Dense(17, kernel_initializer='uniform', activation='relu' , input_dim=37))

#second layer in fc(MLP with two layers)
classifier.add(Dense(17, kernel_initializer='uniform', activation='relu'))


#add output layer
classifier.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))

#compile(optimizing setting)
classifier.compile(loss='binary_crossentropy',optimizer='adam', metrics=['accuracy'])

classifier.fit(x_train,y_train, batch_size=10, epochs=3)

y_pred=classifier.predict(x_test)

Epoch 1/3
11832/11832 [==============================] - 45s 4ms/step - loss: 0.0696 - accuracy: 0.9749
Epoch 2/3
11832/11832 [==============================] - 44s 4ms/step - loss: 0.0018 - accuracy: 0.9998
Epoch 3/3
11832/11832 [==============================] - 44s 4ms/step - loss: 0.0032 - accuracy: 0.9998